export default {
  INCREMENT_COUNTER : "INCREMENT_COUNTER",

  FETCH_REPO_PENDING : "FETCH_REPO_PENDING",
  FETCH_REPO_SUCCESS : "FETCH_REPO_SUCCESS",
  FETCH_REPO_ERROR : "FETCH_REPO_ERROR",

  AUTH_SUCCESS : "AUTH_SUCCESS",
  AUTH_ERROR : "AUTH_ERROR",
}
